### ISSUE TITLE
subject관리 페이지

### ISSUE THREAD

**Issue by NeedIDcard** [omegafrog/TUK-CE-capstone-2023-CognitionTestForConstructionWorkers#66]
조회 - 완료
생성 - 완료
수정 - 진행중
삭제 - 완료

**Comment by NeedIDcard** [comment]
fieldId 전송해도 field 변경이 안됩니다.
그리고 ispassed false인 값이 있어도 risk가 normal로 뜹니다

**Comment by omegafrog** [comment]
수정했습니다. #68
